env:
  # For default users
  # cache_root: "cache"
  # For internal use with persistent storage
  # cache_root: "/export/home/.cache/minigpt4"
  cache_root: "/GPFS/data/haichengwang/Compression/MiniGPT-4/dataset_vqa"
